name: build ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v6
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package and dev requirements 📦
      run: |
        pip3 install .
        pip3 install ".[dev]"
        pip3 install ".[release]"
    - name: run tests ⚙️
      run: python3 tests/run_tests.py
    - name: run flake8 ⚙️
      run: flake8
    - name: build Python package 🏗️
      run: python3 -m build
